project:
  type: book
  output-dir: _book

book:
  title: "`repliMAT`: *A* Guide to Reproducible `MATLAB`"
  author: "David Wilby"
  date: "09/08/2022"
  lang: en-GB
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
    - _license.qmd

bibliography: references.bib

format:
  html:
    from: markdown+emoji
    theme: 
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt



